"""
SQLAlchemy model for DocumentSummary entity.

This module defines the DocumentSummary table structure for storing
cached LLM-generated summaries of medical documents.
"""

from sqlalchemy import Column, Integer, Text, String, DateTime, ForeignKey, JSON
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship
from app.database import Base


class DocumentSummary(Base):
    """
    DocumentSummary model for caching document summaries.
    
    Stores LLM-generated summaries to avoid redundant API calls.
    Cache is invalidated when the source document is updated.
    
    Attributes:
        id: Primary key, auto-incrementing integer
        document_id: Foreign key to documents table (unique)
        summary_text: Cached summary generated by LLM
        model_used: Name of the LLM model used (e.g., 'gpt-4o-mini')
        token_usage: JSON object with token usage details
        created_at: Timestamp when summary was first created
        updated_at: Timestamp when summary was last regenerated
    """
    
    __tablename__ = "document_summary"
    
    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    document_id = Column(Integer, ForeignKey("documents.id", ondelete="CASCADE"), nullable=False, unique=True, index=True)
    summary_text = Column(Text, nullable=False)
    model_used = Column(String(50), nullable=True)
    token_usage = Column(JSON, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)
    
    # Relationship to Document model
    document = relationship("Document", backref="summary", uselist=False)
    
    def __repr__(self) -> str:
        """String representation of DocumentSummary for debugging."""
        return f"<DocumentSummary(id={self.id}, document_id={self.document_id}, model={self.model_used}, updated={self.updated_at})>"

